### PR TITLE
Add HashWithState to increase its scalability

### PR DESCRIPTION
**Pull request by hunshenshi**

### CODE REVIEW

**Comment by jeffprestes** [comment]
Please do not get me wrong on the question, but in which real-world situation would this initial state be helpful? The previous results of other hash would be enough, wouldn't they?

**Comment by mdehoog** [comment]
+1, this would be useful for us too. When hashing more than 16 values, it can be useful to chain hashes together, such that the hash of the last 16 values is the initial state of the next 16. Opened #61 before seeing this one.

**Comment by mdehoog** [comment]
cc @OBrezhniev, would love some eyes on this if possible, thank you in advance!

**Review by OBrezhniev — APPROVED** [review]

**Comment by OBrezhniev** [comment]
LGTM!
@mdehoog Thank you for your contribution!

**Pull request merged**
